### PR TITLE
added transactions to the data bar

### PR DESCRIPTION
**Pull request by miguel-nava**
Since it's working with the `transactionCache` it will initially take 24 hours to fully populate the total number of transactions.
There is a variable `twentyFourHours` on line 286 that you can change to `twentyFourHours = 1000 * 60 * 5` so it'll only track transactions for the past 5 minutes for testing that it works.

### CODE REVIEW

**Comment by miguel-nava** [comment]
May I have an update on the review process? How long does it usually take to review PRs?

**Comment by saizo-nanocafe** [comment]
Hi @miguel-nava , apologies on this inconvenience and the process should have been much quicker but it's been a very busy month. anarkrytpo is really busy this month and unable to do a proper review of your commit. 

Re: I tried testing but even after changing line 286 to show 5 minutes, I wasn't able to see any data pull up on the header for it which is why the commit won't be approved.

Moving forward, the current bounty list will be redone/restarted, there will be a new/dedicated bounty list available through github soon and I hope you aren't too discouraged to give us another chance (after this month and the new bounty list will have more tasks + more XNO available). Again, my apologies on how inconvenient this has been and for getting back to you so late. Since this was from our end, please send your nano address below and I will send the appropriate nano to compensate for your time and for this inconvenience. 

Happy holidays!

**Comment by miguel-nava** [comment]
That's weird that no data popped up. I'll have to run it again and see if I missed anything. 

Thanks for getting back to me. I look forward to the new updated bounty list. 

Nano address: nano_1e45wwpr95t71md8r6afymaqawz3omzo6yiqbyaia9cgg1s3kp7hksud97yo

**Comment by saizo-nanocafe** [comment]
@miguel-nava , updated and currently populating, if your address is the same, email me confirming the address and I'll send your payout!

**Comment by miguel-nava** [comment]
Thank you for adding the changes in. Yes, my address is the same

**Comment by saizo-nanocafe** [comment]
Hi,

I’m still waiting for it to populate, is it possible the transactions are only being pulled from the local node and not the entire nano-network? The transactions are still so low even after 24HRS.

 

Best,

Saizo

**Pull request closed without merging**
